In [2]:
import numpy as np
from scipy import sparse

eye = np.eye(4)
print(f"NumPy array:\n{eye}")

NumPy array:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
sparse_matrix = sparse.csr_matrix(eye)
print(f"\nSciPy sparse CSR matrix:\n{sparse_matrix}")


SciPy sparse CSR matrix:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [5]:
data = np.ones(4)
row_indices = np.arange(4)
col_indices = np.arange(4)
eye_coo = sparse.coo_matrix((data, (row_indices, col_indices)))
print(f"COO representation:\n{eye_coo}")

COO representation:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
